# https://github.com/changesets/action
name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Get NPM Cache Directory Path
        id: npm-cache-dir-path
        run: echo "dir=$(npm config get cache)" >> $GITHUB_ENV
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-npm-
      - name: Install Dependencies
        run: npm ci --prefer-offline --no-audit
      - name: Lint, Format, and Test
        run: npm run lint && npm run pretty
      - name: Install semantic-release Extra Plugins
        run: npm install --save-dev @semantic-release/changelog @semantic-release/git
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release@19.0.5
